program/src/entrypoint.rs
program/src/helpers/delegate.rs
program/src/helpers/merge.rs
program/src/helpers/mod.rs
program/src/lib.rs
program/src/processor.rs

address points raised in initial code review:
* convert `InstructionError` to `ProgramError` without a trait
* use `VoteState::deserialize_into_uninit()`
* drop one lamport borrow before taking another
* rewrite how signers are handled to be clearer and also preserve unfortunate native stake program permissiveness
* add comments for skipped owner checks
also some of the block comments changed but thats because there was a rustfmt rule that messed with comments, which i didnt notice garbled them in a push to master commit lol
after this pr, the most important thing for me to do with the stake program is get solfuzz-agave up and running. currently this repo has better (exhaustive tests for all stake account state combinations for complex operations like split and merge, exhaustive tests for …

program: respond to jon code review

---

Cargo.lock
Cargo.toml
clients/rust/Cargo.toml
clients/rust/src/generated/errors/mod.rs
clients/rust/src/generated/instructions/authorize.rs
clients/rust/src/generated/instructions/authorize_checked.rs
clients/rust/src/generated/instructions/authorize_checked_with_seed.rs
clients/rust/src/generated/instructions/authorize_with_seed.rs
clients/rust/src/generated/instructions/deactivate.rs
clients/rust/src/generated/instructions/deactivate_delinquent.rs
clients/rust/src/generated/instructions/delegate_stake.rs
clients/rust/src/generated/instructions/get_minimum_delegation.rs
clients/rust/src/generated/instructions/initialize.rs
clients/rust/src/generated/instructions/initialize_checked.rs
clients/rust/src/generated/instructions/merge.rs
clients/rust/src/generated/instructions/mod.rs
clients/rust/src/generated/instructions/set_lockup.rs
clients/rust/src/generated/instructions/set_lockup_checked.rs
clients/rust/src/generated/instructions/split.rs
clients/rust/src/generated/instructions/withdraw.rs
clients/rust/src/generated/mod.rs
clients/rust/src/generated/programs.rs
clients/rust/src/generated/types/mod.rs
clients/rust/src/generated/types/stake_authorize.rs
package.json
pnpm-lock.yaml
program/Cargo.toml
scripts/generate-clients.mjs

Local build/CI are currently not working since `v2.1` moved to a branch now.
Bump the dependencies for both the program and Rust client to use the version from `crates.io`.
The generated Rust client changed since the `@codama/renderer-rust` version was bumped to remove the dependency on Anchor.

Bump dependencies

---

interface/src/config.rs
interface/src/instruction.rs
interface/src/lib.rs
interface/src/stake_flags.rs
interface/src/stake_history.rs
interface/src/state.rs
interface/src/tools.rs

The initial PR #10 adds the Stake interface files from the SDK without their git history.
Copy the files from the SDK together with their associated history using `git-filter-repo`:
```
git remote add agave https://github.com/anza-xyz/agave.git
git fetch agave master:stake-from-agave
git switch stake-from-agave
git remote rm agave
python3 ../git-filter-repo \
--path sdk/program/src/stake/config.rs \
--path sdk/program/src/stake/instruction.rs  \
--path sdk/program/src/stake/mod.rs \
--path sdk/program/src/stake/stake_flags.rs \
--path sdk/program/src/stake/state.rs \
--path sdk/program/src/stake/tools.rs \
--path sdk/program/src/stake_history.rs \
--path-rename sdk/program/src/stake/config.rs:interface/src/config.rs \
--path-rename …
```

interface: Add stake files from sdk with history

---

interface/src/config.rs
interface/src/instruction.rs
interface/src/lib.rs
interface/src/stake_flags.rs
interface/src/stake_history.rs
interface/src/state.rs
interface/src/tools.rs

PR #12 was "squashed & merged", which does not preserve the history.
This PR re-adds the files so they can be "rebased & merged" instead. PR #15 reverted #12.

interface: Re-add stake files from sdk with history

---

Cargo.lock
Cargo.toml
interface/Cargo.toml
interface/src/config.rs
interface/src/error.rs
interface/src/instruction.rs
interface/src/lib.rs
interface/src/stake_flags.rs
interface/src/stake_history.rs
interface/src/state.rs
interface/src/tools.rs

While the repository contains the source files for the Stake interface, it does not define the interface crate.
This PR adds the interface `Cargo.toml` configuration and updates its dependencies to use the individual crates.
There are 2 aspects that will be handled in separate PRs:
1. Interface scripts for the CI: this will be added once https://github.com/solana-program/system/pull/23 is merged, since it will follow a similar pattern.
2. Move the [`StakeHistory`](https://github.com/anza-xyz/agave/blob/master/sdk/program/src/sysvar/stake_history.rs) sysvar into this repository.

Add interface crate

---

clients/js/package.json

Version 0.1.0 of the JS client was published on NPM in the "Publish JS Client" GitHub Action. However, because of branch protection rules, the Action failed to push the version change to the `main` branch. I'm investigating ways to bypass some protection rules for some Actions but, in the meantime, the record needs to be set straight on the JS client version.

Bump JS client to 0.1.0

---

Cargo.lock
interface/Cargo.toml

Currently the interface crate doesn't compile with `cargo build -F bincode` because it's missing `solana-system-interface/bincode`

fix bincode feature

---

Cargo.lock
interface/Cargo.toml
interface/src/stake_history.rs

This trait impl needs to be in either solana-stake-interface or solana-sysvar-id because of the orphan rule. The interface crate is the obvious choice because it would add a bunch of deps to solana-sysvar-id

interface: impl SysvarId for StakeHistory

---

Cargo.lock
interface/Cargo.toml

This PR bumps the `interface` crate version to `1.1` since a new dependency was added.

interface: Bump version

---

Cargo.lock
interface/Cargo.toml

This PR bumps the interface crate version to `1.2` since the `solana-program-error` dependency is not optional anymore. It is required since `StakeError` implements the `From` trait to convert an error to a `ProgramError`.

interface: Bump version to `v1.2`

---

.github/workflows/main.yml
.github/workflows/publish-rust-crate.yml
scripts/rust.mts

This PR refactors the `publish-rust-client` to allow publishing rust crates for the repository (e.g., `interface`, `clients/rust`).

ci: Refactor publish rust crate

---

Cargo.lock
interface/Cargo.toml

The refactored "publish-rust-crate" workflow uses `cargo release` to bump the version of the crate before publishing. Since the `solana-stake-interface` crate version was already bump manually, using the workflow would bump the version again.
Revert the manual version bump so the workflow can be used to publish the next `solana-stake-interface` crate.

Revert version bump

---

.github/workflows/main.yml
.github/workflows/publish-rust-crate.yml
Cargo.toml

The "publish" workflow is missing a `npx` command in order to run the `tsx` scripts; additionally, the `build` toolchain is not being set.
Add the missing command and toolchain definition.
A "dry-run" of the workflow now works: https://github.com/solana-program/stake/actions/runs/13001907231

ci: Fix publish workflow

---

.github/workflows/publish-rust-crate.yml

This PR fixes a small typo in a job name.

ci: Fix typo on publish crate workflow

---

interface/src/instruction.rs

This module was incorrectly using the system program ID instead of the stake program ID

use correct program ID in solana_stake_interface::instruction

---

interface/README.md
scripts/rust.mts

While the `publish-rust-crate` can successfully publish a crate, it fails to create a git tag and GitHub release due to using the wrong path to look up the `Cargo.toml` file.
Fix the `Cargo.toml` look up by using the correct value. It also fixes the docs link on the `README.md` of the interface crate.

publish: Fix workflow

---

.github/workflows/publish-rust-crate.yml
scripts/helpers/utils.mts
scripts/rust.mts

Currently there is a problem in how the crate name parsing is done on the publish crate workflow – it fails to determine the correct path for the crate, which prevents the script to parse the name and version of the crate.
Modify the `parseCliArguments` to return the original `relativePath` value so that the script can parse the name and version of the crate.

publish: Fix crate name parsing

---

Cargo.lock
program/Cargo.toml
program/tests/program_test.rs

solana_program 2.1.10 is a hard minimum requirement due to work done on builtin compute usage
this completes the work started by #49 and #50 to fix breakage from upstream that went unnoticed. #51 (yet to land) will start running program tests in ci
when the Great Monorepo Cleftishment is complete we should start thinking about adding the bpf programs as downstream repos, because if this happens again it would be because we went from "ci doesnt run tests" to "ci doesnt run often enough because we dont need to make changes to the code"

program: update to 2.1.10

---

Cargo.lock
program/Cargo.toml
program/tests/interface.rs

this adds tests that attempt to exhaustively check the interfaces of every stake instruction, to make up for gaps in coverage from the existing tests, particularly with lockups

Interface tests

---

clients/js/src/generated/instructions/authorize.ts
clients/js/src/generated/instructions/authorizeChecked.ts
clients/js/src/generated/instructions/authorizeCheckedWithSeed.ts
clients/js/src/generated/instructions/authorizeWithSeed.ts
clients/js/src/generated/instructions/deactivate.ts
clients/js/src/generated/instructions/deactivateDelinquent.ts
clients/js/src/generated/instructions/delegateStake.ts
clients/js/src/generated/instructions/initialize.ts
clients/js/src/generated/instructions/initializeChecked.ts
clients/js/src/generated/instructions/merge.ts
clients/js/src/generated/instructions/moveLamports.ts
clients/js/src/generated/instructions/moveStake.ts
clients/js/src/generated/instructions/setLockup.ts
clients/js/src/generated/instructions/setLockupChecked.ts
clients/js/src/generated/instructions/split.ts
clients/js/src/generated/instructions/withdraw.ts
clients/rust/src/generated/instructions/authorize.rs
clients/rust/src/generated/instructions/authorize_checked.rs
clients/rust/src/generated/instructions/authorize_checked_with_seed.rs
clients/rust/src/generated/instructions/authorize_with_seed.rs
clients/rust/src/generated/instructions/set_lockup_checked.rs
clients/rust/src/generated/instructions/withdraw.rs
package.json
scripts/helpers/generate-clients.mts

When converting an Anchor IDL to a Codama IDL, the adapter defaults to using the `"programId"` optional account strategy for all instructions. This allows positional optional accounts as introduced in Anchor which means when an account is not provided, it is replaced by the program ID to only used a single byte in the transaction.
However, this is not the appropriate optional account strategy for the stake account as it simply omits optional accounts. Therefore, this PR replaces the `optionalAccountStrategy` of all instructions to the `"omitted"` strategy.
This in turns updates the generated code to be more accurate when creating and parsing instructions.
Note that, I've had to adjust the `generate:clients` script slightly so it calls `pnpm format:fix` because the Prettier used …

Use omitted optional account strategy on IDL

---

program/tests/stake_instruction.rs

all clusters are running the bpf stake program, so we can stop testing native stake. native stake is in the process of being removed from the agave repo but we actually can remove these tests now,since they exist in agave and will not be removed from there until native stake is removed!
this will let us continue with #82 because we no longer assert behavior of native and bpf stake agree

tests: remove native stake test cases

---

interface/src/stake_history.rs

#81 improved the performance of stake history `get()`. it uses a subtraction now so its prudent to test we get `None` on an epoch greater than the newest one

interface: test both sides of stake history
